version: '3.3'
services:
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=onlineStore
      - MYSQL_ROOT_PASSWORD=111111


    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

  mystore-app:
    image: vladoap/mystore:v1
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - SQL_USERNAME=root
      - SQL_PASSWORD=
      - CLOUDINARY_API_KEY=
      - CLOUDINARY_API_SECRET=
      - CLOUDINARY_CLOUD_NAME=

    depends_on:
      db:
        condition: service_healthy

