spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver

    # for deployment to azure
#    url: jdbc:mysql://mystore-db.mysql.database.azure.com:3306/mystore-db?allowPublicKeyRetrieval=true&sslMode=REQUIRED&createDatabaseIfNotExist=true&serverTimezone=UTC

    # for spring app
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/onlineStore?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"

    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true


  sql:
    init:
      mode: always

  jpa:

    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true



  #Cloudinary Properties
cloudinary:
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  cloud-name: ${CLOUDINARY_CLOUD_NAME}


#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.security: DEBUG


# every midnight
schedulers:
  cron: "0 0 0 * * *"


